import type { ModifierStats, ModifierStatKey } from "@/lib/build/stats";

export const modifierLabels: Record<ModifierStatKey, string> = {
  CRIT_RATE_PCT: "Crit Rate",
  CRIT_DMG_PCT: "Crit DMG%",
  ULT_GAIN_PCT: "Ultimate Gain%",
  ULTIMATE_COST_REDUCTION_PCT: "Ultimate Cost Reduction%",
  MAIN_ATTR_PCT: "Main Attribute%",
  SECONDARY_ATTR_PCT: "Secondary Attribute%",
  ARTS_INTENSITY: "Arts Intensity",
  ATK_PCT: "ATK%",
  ALL_DMG_PCT: "DMG%",
  FLAT_ATK: "Flat ATK",
  FLAT_HP: "Flat HP",
  HP_PCT: "HP%",
  PHYSICAL_DMG_PCT: "Physical DMG%",
  ARTS_DMG_PCT: "Arts DMG%",
  HEAT_NATURE_DMG_PCT: "Heat/Nature DMG%",
  HEAT_DMG_PCT: "Heat DMG%",
  CRYO_DMG_PCT: "Cryo DMG%",
  ELECTRIC_DMG_PCT: "Electric DMG%",
  NATURE_DMG_PCT: "Nature DMG%",
  BASIC_ATK_DMG_PCT: "Basic Attack DMG%",
  SKILL_DMG_PCT: "Skill DMG%",
  BATTLE_SKILL_DMG_PCT: "Battle Skill DMG%",
  COMBO_SKILL_DMG_PCT: "Combo Skill DMG%",
  ULTIMATE_DMG_PCT: "Ultimate DMG%",
  DMG_TAKEN_PCT: "DMG Taken%",
  ARTS_DMG_TAKEN_PCT: "Arts DMG Taken%",
  PHYSICAL_DMG_TAKEN_PCT: "Physical DMG Taken%",
  HEAT_DMG_TAKEN_PCT: "Heat DMG Taken%",
  CRYO_DMG_TAKEN_PCT: "Cryo DMG Taken%",
  ELECTRIC_DMG_TAKEN_PCT: "Electric DMG Taken%",
  NATURE_DMG_TAKEN_PCT: "Nature DMG Taken%",
  AETHER_DMG_TAKEN_PCT: "Aether DMG Taken%",
  PHYSICAL_RESIST_PCT: "Physical RES%",
  HEAT_RESIST_PCT: "Heat RES%",
  CRYO_RESIST_PCT: "Cryo RES%",
  ELECTRIC_RESIST_PCT: "Electric RES%",
  NATURE_RESIST_PCT: "Nature RES%",
  AETHER_RESIST_PCT: "Aether RES%",
  PHYSICAL_RESIST_IGNORE_PCT: "Physical RES Ignore%",
  HEAT_RESIST_IGNORE_PCT: "Heat RES Ignore%",
  CRYO_RESIST_IGNORE_PCT: "Cryo RES Ignore%",
  ELECTRIC_RESIST_IGNORE_PCT: "Electric RES Ignore%",
  NATURE_RESIST_IGNORE_PCT: "Nature RES Ignore%",
  AETHER_RESIST_IGNORE_PCT: "Aether RES Ignore%",
  HEALING_PCT: "Treatment Efficiency",
  HEALING_RECEIVED_PCT: "Treatment Received Bonus",
  FINAL_DMG_REDUCTION_PCT: "Final DMG Reduction%",
  PHYSICAL_SUS_PCT: "Physical Susceptibility%",
  ARTS_SUS_PCT: "Arts Susceptibility%",
  HEAT_SUS_PCT: "Heat Susceptibility%",
  CRYO_SUS_PCT: "Cryo Susceptibility%",
  ELECTRIC_SUS_PCT: "Electric Susceptibility%",
  NATURE_SUS_PCT: "Nature Susceptibility%",
  AETHER_SUS_PCT: "Aether Susceptibility%",
  DMG_VS_STAGGERED_PCT: "DMG vs. Staggered%",
};

const defaults: ModifierStats = {
  CRIT_RATE_PCT: 0.05,
  CRIT_DMG_PCT: 0.50,
  ULT_GAIN_PCT: 1.0,
  ULTIMATE_COST_REDUCTION_PCT: 0,
  MAIN_ATTR_PCT: 0,
  SECONDARY_ATTR_PCT: 0,
  ARTS_INTENSITY: 0,
  ATK_PCT: 0,
  ALL_DMG_PCT: 0,
  FLAT_ATK: 0,
  FLAT_HP: 0,
  HP_PCT: 0,
  PHYSICAL_DMG_PCT: 0,
  ARTS_DMG_PCT: 0,
  HEAT_NATURE_DMG_PCT: 0,
  HEAT_DMG_PCT: 0,
  CRYO_DMG_PCT: 0,
  ELECTRIC_DMG_PCT: 0,
  NATURE_DMG_PCT: 0,
  BASIC_ATK_DMG_PCT: 0,
  SKILL_DMG_PCT: 0,
  BATTLE_SKILL_DMG_PCT: 0,
  COMBO_SKILL_DMG_PCT: 0,
  ULTIMATE_DMG_PCT: 0,
  DMG_TAKEN_PCT: 0,
  ARTS_DMG_TAKEN_PCT: 0,
  PHYSICAL_DMG_TAKEN_PCT: 0,
  HEAT_DMG_TAKEN_PCT: 0,
  CRYO_DMG_TAKEN_PCT: 0,
  ELECTRIC_DMG_TAKEN_PCT: 0,
  NATURE_DMG_TAKEN_PCT: 0,
  AETHER_DMG_TAKEN_PCT: 0,
  PHYSICAL_RESIST_PCT: 0,
  HEAT_RESIST_PCT: 0,
  CRYO_RESIST_PCT: 0,
  ELECTRIC_RESIST_PCT: 0,
  NATURE_RESIST_PCT: 0,
  AETHER_RESIST_PCT: 0,
  PHYSICAL_RESIST_IGNORE_PCT: 0,
  HEAT_RESIST_IGNORE_PCT: 0,
  CRYO_RESIST_IGNORE_PCT: 0,
  ELECTRIC_RESIST_IGNORE_PCT: 0,
  NATURE_RESIST_IGNORE_PCT: 0,
  AETHER_RESIST_IGNORE_PCT: 0,
  HEALING_PCT: 0,
  HEALING_RECEIVED_PCT: 0,
  FINAL_DMG_REDUCTION_PCT: 0,
  PHYSICAL_SUS_PCT: 0,
  ARTS_SUS_PCT: 0,
  HEAT_SUS_PCT: 0,
  CRYO_SUS_PCT: 0,
  ELECTRIC_SUS_PCT: 0,
  NATURE_SUS_PCT: 0,
  AETHER_SUS_PCT: 0,
  DMG_VS_STAGGERED_PCT: 0,
};

export function displayModifierEntries(mods: ModifierStats) {
  return (Object.keys(mods) as ModifierStatKey[])
    .filter((k) => mods[k] !== defaults[k])
    .map((k) => ({
      key: k,
      label: modifierLabels[k],
      value: k.endsWith("PCT") ? `${(mods[k] * 100).toFixed(1)}%` : `${mods[k].toFixed(1)}`,
    }));
}
