import type { ModifierStats, ModifierStatKey } from "@/lib/build/stats";

export const modifierLabels: Record<ModifierStatKey, string> = {
  CRIT_RATE_PCT: "Crit Rate",
  CRIT_DMG_PCT: "Crit DMG%",
  ULT_GAIN_PCT: "Ultimate Gain%",
  MAIN_ATTR_PCT: "Main Attribute%",
  SECONDARY_ATTR_PCT: "Secondary Attribute%",
  ARTS_INTENSITY: "Arts Intensity",
  ATK_PCT: "ATK%",
  FLAT_ATK: "Flat ATK",
  HP_PCT: "HP%",
  PHYSICAL_DMG_PCT: "Physical DMG%",
  ARTS_DMG_PCT: "Arts DMG%",
  HEAT_DMG_PCT: "Heat DMG%",
  CRYO_DMG_PCT: "Cryo DMG%",
  ELECTRIC_DMG_PCT: "Electric DMG%",
  NATURE_DMG_PCT: "Nature DMG%",
  BASIC_ATK_DMG_PCT: "Basic Attack DMG%",
  SKILL_DMG_PCT: "Skill DMG%",
  BATTLE_SKILL_DMG_PCT: "Battle Skill DMG%",
  COMBO_SKILL_DMG_PCT: "Combo Skill DMG%",
  ULTIMATE_DMG_PCT: "Ultimate DMG%",
  DMG_TAKEN_PCT: "DMG Taken%",
  PHYSICAL_RESIST_PCT: "Physical RES%",
  HEAT_RESIST_PCT: "Heat RES%",
  CRYO_RESIST_PCT: "Cryo RES%",
  ELECTRIC_RESIST_PCT: "Electric RES%",
  NATURE_RESIST_PCT: "Nature RES%",
  AETHER_RESIST_PCT: "Aether RES%",
  HEALING_PCT: "Treatment Efficiency",
  PHYSICAL_SUS_PCT: "Physical Susceptibility%",
  ARTS_SUS_PCT: "Arts Susceptibility%",
  HEAT_SUS_PCT: "Heat Susceptibility%",
  CRYO_SUS_PCT: "Cryo Susceptibility%",
  ELECTRIC_SUS_PCT: "Electric Susceptibility%",
  NATURE_SUS_PCT: "Nature Susceptibility%",
};

const defaults: ModifierStats = {
  CRIT_RATE_PCT: 0.05,
  CRIT_DMG_PCT: 0.50,
  ULT_GAIN_PCT: 1.0,
  MAIN_ATTR_PCT: 0,
  SECONDARY_ATTR_PCT: 0,
  ARTS_INTENSITY: 0,
  ATK_PCT: 0,
  FLAT_ATK: 0,
  HP_PCT: 0,
  PHYSICAL_DMG_PCT: 0,
  ARTS_DMG_PCT: 0,
  HEAT_DMG_PCT: 0,
  CRYO_DMG_PCT: 0,
  ELECTRIC_DMG_PCT: 0,
  NATURE_DMG_PCT: 0,
  BASIC_ATK_DMG_PCT: 0,
  SKILL_DMG_PCT: 0,
  BATTLE_SKILL_DMG_PCT: 0,
  COMBO_SKILL_DMG_PCT: 0,
  ULTIMATE_DMG_PCT: 0,
  DMG_TAKEN_PCT: 0,
  PHYSICAL_RESIST_PCT: 0,
  HEAT_RESIST_PCT: 0,
  CRYO_RESIST_PCT: 0,
  ELECTRIC_RESIST_PCT: 0,
  NATURE_RESIST_PCT: 0,
  AETHER_RESIST_PCT: 0,
  HEALING_PCT: 0,
  PHYSICAL_SUS_PCT: 0,
  ARTS_SUS_PCT: 0,
  HEAT_SUS_PCT: 0,
  CRYO_SUS_PCT: 0,
  ELECTRIC_SUS_PCT: 0,
  NATURE_SUS_PCT: 0,
};

export function displayModifierEntries(mods: ModifierStats) {
  return (Object.keys(mods) as ModifierStatKey[])
    .filter((k) => mods[k] !== defaults[k])
    .map((k) => ({
      key: k,
      label: modifierLabels[k],
      value: `${(mods[k] * 100).toFixed(1)}%`,
    }));
}